export const demoData = [
  {
    id: "1",
    title: "Demo Title 1",
    description: "Demo description 1",
    category: "entertainment",
    blogData: "<h1>Demo Story 1</h1>",
    created: Date(),
    like: false,
  },
  {
    id: "2",
    title: "Demo Title 2",
    description: "Demo description 2",
    category: "health",
    blogData: "<h1>Demo Story 2</h1>",
    created: Date(),
    like: false,
  },
  {
    id: "3",
    title: "Demo Title 3",
    description: "Demo description 3",
    category: "programming",
    blogData: "<h1>Demo Story 3</h1>",
    created: Date(),
    like: false,
  },
  {
    id: "4",
    title: "Demo Title 4",
    description: "Demo description 4",
    category: "health",
    blogData: "<h1>Demo Story 4</h1>",
    created: Date(),
    like: false,
  },
  {
    id: "5",
    title: "Demo Title 5",
    description: "Demo description 5",
    category: "programming",
    blogData: "<h1>Demo Story 5</h1>",
    created: Date(),
    like: false,
  },
  {
    id: "6",
    title: "Demo Title 6",
    description: "Demo description 6",
    category: "programming",
    blogData: "<h1>Demo Story 6</h1>",
    created: Date(),
    like: false,
  },
  {
    id: "7",
    title: "Demo Title 7",
    description: "Demo description 7",
    category: "health",
    blogData: "<h1>Demo Story 7</h1>",
    created: Date(),
    like: false,
  },
  {
    id: "8",
    title: "Demo Title 8",
    description: "Demo description 8",
    category: "health",
    blogData: "<h1>Demo Story 8</h1>",
    created: Date(),
    like: false,
  },
  {
    id: "9",
    title: "Demo Title 9",
    description: "Demo description 9",
    category: "programming",
    blogData: "<h1>Demo Story 9</h1>",
    created: Date(),
    like: false,
  },
  {
    id: "10",
    title: "Demo Title 10",
    description: "Demo description 10",
    category: "health",
    blogData: "<h1>Demo Story 10</h1>",
    created: Date(),
    like: false,
  },
  {
    id: "11",
    title: "Demo Title 11",
    description: "Demo description 11",
    category: "sports",
    blogData: "<h1>Demo Story 11</h1>",
    created: Date(),
    like: false,
  },
  {
    id: "12",
    title: "Demo Title 12",
    description: "Demo description 12",
    category: "programming",
    blogData: "<h1>Demo Story 12</h1>",
    created: Date(),
    like: false,
  },
  {
    id: "13",
    title: "Demo Title 13",
    description: "Demo description 13",
    category: "sports",
    blogData: "<h1>Demo Story 13</h1>",
    created: Date(),
    like: false,
  },
  {
    id: "14",
    title: "Demo Title 14",
    description: "Demo description 14",
    category: "health",
    blogData: "<h1>Demo Story 14</h1>",
    created: Date(),
    like: false,
  },
  {
    id: "15",
    title: "Demo Title 15",
    description: "Demo description 15",
    category: "sports",
    blogData: "<h1>Demo Story 15</h1>",
    created: Date(),
    like: false,
  },
  {
    id: "16",
    title: "Demo Title 16",
    description: "Demo description 16",
    category: "entertainment",
    blogData: "<h1>Demo Story 16</h1>",
    created: Date(),
    like: false,
  },
  {
    id: "17",
    title: "Demo Title 17",
    description: "Demo description 17",
    category: "sports",
    blogData: "<h1>Demo Story 17</h1>",
    created: Date(),
    like: false,
  },
  {
    id: "18",
    title: "Demo Title 18",
    description: "Demo description 18",
    category: "business",
    blogData: "<h1>Demo Story 18</h1>",
    created: Date(),
    like: false,
  },
  {
    id: "19",
    title: "Demo Title 19",
    description: "Demo description 19",
    category: "entertainment",
    blogData: "<h1>Demo Story 19</h1>",
    created: Date(),
    like: false,
  },
  {
    id: "20",
    title: "Demo Title 20",
    description: "Demo description 20",
    category: "sports",
    blogData: "<h1>Demo Story 20</h1>",
    created: Date(),
    like: false,
  },
  {
    id: "21",
    title: "Demo Title 21",
    description: "Demo description 21",
    category: "business",
    blogData: "<h1>Demo Story 21</h1>",
    created: Date(),
    like: false,
  },
  {
    id: "22",
    title: "Demo Title 22",
    description: "Demo description 22",
    category: "business",
    blogData: "<h1>Demo Story 22</h1>",
    created: Date(),
    like: false,
  },
  {
    id: "23",
    title: "Demo Title 23",
    description: "Demo description 23",
    category: "sports",
    blogData: "<h1>Demo Story 23</h1>",
    created: Date(),
    like: false,
  },
  {
    id: "24",
    title: "Demo Title 24",
    description: "Demo description 24",
    category: "entertainment",
    blogData: "<h1>Demo Story 24</h1>",
    created: Date(),
    like: false,
  },
  {
    id: "25",
    title: "Demo Title 25",
    description: "Demo description 25",
    category: "sports",
    blogData: "<h1>Demo Story 25</h1>",
    created: Date(),
    like: false,
  },
  {
    id: "26",
    title: "Demo Title 26",
    description: "Demo description 26",
    category: "business",
    blogData: "<h1>Demo Story 26</h1>",
    created: Date(),
    like: false,
  },
  {
    id: "27",
    title: "Demo Title 27",
    description: "Demo description 27",
    category: "entertainment",
    blogData: "<h1>Demo Story 27</h1>",
    created: Date(),
    like: false,
  },
  {
    id: "28",
    title: "Demo Title 28",
    description: "Demo description 28",
    category: "entertainment",
    blogData: "<h1>Demo Story 28</h1>",
    created: Date(),
    like: false,
  },
  {
    id: "29",
    title: "Demo Title 29",
    description: "Demo description 29",
    category: "business",
    blogData: "<h1>Demo Story 29</h1>",
    created: Date(),
    like: false,
  },
  {
    id: "30",
    title: "Demo Title 30",
    description: "Demo description 30",
    category: "entertainment",
    blogData: "<h1>Demo Story 30</h1>",
    created: Date(),
    like: false,
  },
];
